[package]
name = "spin-environments"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = "0.1"
bytes = { workspace = true }
chrono = { workspace = true }
dirs = { workspace = true }
futures = "0.3"
futures-util = "0.3"
id-arena = "2"
indexmap = "2"
oci-client = { version = "0.16", default-features = false, features = ["native-tls"] }
oci-wasm = "0.4"
reqwest = { workspace = true }
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
spin-common = { path = "../common" }
spin-componentize = { path = "../componentize" }
spin-compose = { path = "../compose" }
spin-loader = { path = "../loader" }
spin-manifest = { path = "../manifest" }
spin-serde = { path = "../serde" }
toml = { workspace = true }
tokio = { version = "1.23", features = ["fs"] }
tracing = { workspace = true }
url = { workspace = true }
wac-graph = "0.8"
wac-types = "0.8"
wasm-pkg-client = { workspace = true }
wasmparser = { workspace = true }
wit-component = { workspace = true }
wit-parser = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
wit-component = { workspace = true, features = ["dummy-module"] }
wit-encoder = "0.235"

[lints]
workspace = true
