[package]
name = "spin-oci"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-compression = { version = "0.4", features = ["gzip", "tokio"] }
async-tar = "0.5"
base64 = { workspace = true }
chrono = { workspace = true }
# Fork with updated auth to support ACR login
# Ref https://github.com/camallo/dkregistry-rs/pull/263
dirs = { workspace = true }
dkregistry = { git = "https://github.com/fermyon/dkregistry-rs", rev = "161cf2b66996ed97c7abaf046e38244484814de3" }
docker_credential = "1"
futures-util = { workspace = true }
itertools = { workspace = true }
oci-client = { git = "https://github.com/vdice/oci-distribution", rev = "d8ec6b0da31ac5d6ca61f8910c0e952858723d43" }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
spin-common = { path = "../common" }
spin-compose = { path = "../compose" }
spin-loader = { path = "../loader" }
spin-locked-app = { path = "../locked-app" }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["fs"] }
tokio-util = { version = "0.7", features = ["compat"] }
tracing = { workspace = true }
walkdir = { workspace = true }
wasmparser = { workspace = true }
wat = "1"

[dev-dependencies]
wasm-encoder = { workspace = true }
wit-component = { workspace = true, features = ["dummy-module"] }
wit-parser = { workspace = true }
