name: Dispatch Event

on:
  push:
    branches: [main, "v*"]
    tags: ["v*"]

jobs:
  dispatch-rust-docs:
    name: Dispatch rust-docs spin-update event
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'fermyon' }}
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DEST_REPO_ACCESS_TOKEN }}
          repository: fermyon/rust-docs
          event-type: spin-update
          client-payload: '{"ref": "${{ github.ref_name }}"}'

  dispatch-homebrew-tap:
    name: Dispatch spin-release event to fermyon/homebrew-tap
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'fermyon' }} && ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DEST_REPO_ACCESS_TOKEN }}
          repository: fermyon/homebrew-tap
          event-type: spin-release
          client-payload: '{"version": "${{ github.ref_name }}"}'